- src/main/java/ku/user/user/infrastructure/Password.java
- src/main/java/ku/user/user/infrastructure/UserEntity.java
- src/main/java/ku/user/user/infrastructure/UserJpaRepository.java
- src/main/java/ku/user/user/infrastructure/UserJpaRepositoryImpl.java
- src/main/java/ku/user/user/infrastructure/UserRepository.java
- src/main/java/ku/user/user/infrastructure/UserStatus.java
- src/main/java/ku/user/user/infrastructure/exception/InvalidPasswordException.java
- src/test/java/ku/user/user/infrastructure/PasswordTest.java
- src/test/java/ku/user/user/infrastructure/UserJpaRepositoryImplTest.java
infrastructure에 해당하는 UserEntity 생성 및 test 추가
1. infrastructure에 해당하는 UserEntity와 임베디드 타입 Password 생성
2. UserEntity 내에서 password 역할을 password 클래스 생성으로 분리
3. password 역할에 대해 test code 진행(통과 완료)
- 해당 코드의 테스트 작성이 힘들다면 해당 구조가 잘못되었을 수도 있다.
> [Feat] UserEntity & Password

- src/main/java/ku/user/user/infrastructure/repository/UserRepositoryImpl.java
UserRepositoryImpl 이름 변경
1. UserRepositoryImpl 이름 변경
- 없음
> [Refact] Repo 클래스 이름 변경

- .github/workflows/deploy-ku-cd.yml
- .github/workflows/deploy-ku-ci.yml
- infra/docker/Dockerfile
- src/main/java/ku/user/user/infrastructure/entity/UserEntity.java
- src/main/resources/application.yml
- src/test/java/ku/user/user/infrastructure/UserRepositoryImplTest.java
- src/test/java/ku/user/user/service/UserServiceImplTest.java
앞으로 있을 ci/cd를 위하여 workflow를 추가하였습니다. 또한 기존에는 없던 oauth 설정 또한 추가하였습니다.
1. ci/cd 작업을 위하여 각각의 yml 파일을 추가하였습니다. 또한 cd 작업 시 docker image를 docker hub에 올리고 서버에서는 그 이미지를 받아와 실행을 하기에 docker 파일을 추가하였습니다.
2. oauth에 대한 다른 파일들은 예전에 올렸지만 yml 설정을 올리지 않았었기에 해당 파일을 수정하였습니다.
- 언리얼에서는 어떻게 동작하는거지..
- 또한 궁금한 점이 현재 테스트 코드에서 엔티티를 생성하는 부분이 있습니다. 하지만 엔티티 레벨은 protected 레벨이기에 생성이 불가능하죠. 이걸 위해서 팩토리 메서드 하나를 만들어서 처리했는데 이게 맞는 방식일까요? 더 좋은 방법이 있는거 같은데 떠오르지가 않네요...
> [Feat] ci/cd 추가 및 oauth 환경 설정

- src/main/java/ku/user/config/WebConfig.java
CORS config 추가를 하였습니다.
1. kakao login을 할 경우 새로 페이지를 띄우고 리다이렉트하여 작업이 이루어지는데 이것이 cors 정책에 걸리는거 같습니다. 그렇기에 cors 설정을 추가하였습니다. cors에 대해 간단히 공부한 내용을 같이 첨부하겠습니다. spring 공식 문서를 보니 cors 설정 방법도 하나가 아니더군요.
https://ambiguous-patio-117.notion.site/cors-4127d1cfa1a7429fbe90d0f8d2532085?pvs=4
- 냉무
> [feat] CORS config 설정 추가

- src/main/resources/application.yml
kakao redirect url 변경
1. 기존의 경우 redirect가 localhost로 되어 있어 정상적으로 로직이 동작하지 않았지만 이것을 배포 서버의 주소로 변경하였습니다.
- 냉무
> [Refact] kakao redirect url 변경

- build.gradle
- infra/docker/user.yml
- src/main/resources/application.yml
k8s 설정 추가
1. 쿠버네티스로 가기 위한 설정 파일을 추가했습니다. secret 파일을 k8s에서는 따로 관리하여 주입할 수 있는데 이 파일은 일단 올리지 않았습니다.
- 현재는 비용적인 문제로 안하지만 추후 서버를 빌린다면 다시 넘어갈 수 있게 파일은 유지할 생각입니다.
> [Feat] k8s 설정 추가

- .github/workflows/deploy-ku-cd.yml
- src/main/resources/application.yml
자동 배포 설정
1. 작업 분류와 크게 다른 점은 없습니다.
- api-gateway, game-server,discovery는 같은 서버(서버 1) config, user 같은 서버(서버 2) <- 이렇게 서버를 구축할 예정에 있으며 아키텍처 그림은 노션에 올려두겠습니다.
> [CI/CD] user 서버 자동 배포 설정

- infra/docker/Dockerfile
> [Fix] 도커 파일 profile 변경

- .github/workflows/deploy-ku-cd.yml
- src/main/resources/bootstrap.yml
> [Fix] config pull error 수정

- infra/docker/Dockerfile
> [Fix] image 환경 변수 제거

- src/main/resources/bootstrap.yml
> [fix] config 서버 파일 이름 변경

- .github/workflows/deploy-ku-cd.yml
- infra/docker/Dockerfile
- src/main/java/ku/user/user/controller/UserController.java
- src/main/resources/bootstrap.yml
secret 기능 추가
1. config 데이터는 결국 통신을 통하여 이동을 하는데 이 과정에서 데이터가 노출되지 않게 암호화를 설정하였습니다.
- 냉무
> [Feat] secret 기능 추가

- src/main/java/ku/user/security/SecurityConfig.java
OAuth 설정 삭제
1. OAuth와 security 설정 충돌로 삭제
- 냉무
> [Delete] OAuth 설정 삭제

- src/main/java/ku/user/domain/character/domain/CharacterType.java
> CharacterType 변경

- .github/workflows/deploy-ku-cd.yml
- build.gradle
- src/main/resources/application.yml
> [Feat] RDS 전환

- .github/workflows/deploy-ku-cd.yml
> [fix] cd script

- src/main/java/ku/user/domain/character/domain/Character.java
- src/main/java/ku/user/domain/inventory/domain/Inventory.java
- src/main/java/ku/user/domain/inventory/dto/request/PutItemRequest.java
- src/main/java/ku/user/domain/inventory/dto/response/GetInventoryResponse.java
- src/main/java/ku/user/domain/inventory/service/InventoryService.java
- src/main/java/ku/user/domain/quest/service/QuestService.java
- src/main/java/ku/user/domain/quest/util/QuestUtil.java
- 각종 버그 수정
1. X
- 원래 캐릭터 변경시 재화가 유지되지 않도록 설정하였는데 회의가 필요할 거 같습니다. 초기 설계에는 재화가 유지 되지 않도록 하는 맞는데 구현을 기존 캐릭터를 지워버리도록 제가 구현했네요 ;;
> [Bug] 퀘스트, 재화, 아이템

- src/main/java/ku/user/domain/inventory/exception/NoPurchasedItemException.java
- src/main/java/ku/user/domain/inventory/service/InventoryService.java
- src/main/java/ku/user/global/exception/ErrorCode.java
- 버그 수정
- NoPurchasedItemException 추가
> [Feat] NoPurchasedItemException 추가 & 버그 수정

- .github/workflows/deploy-ku-cd.yml
> [fix] 도커 볼륨 지정

- src/main/java/ku/user/domain/ranking/service/RankingServiceImpl.java
ranking 오류 수정
1.  ranking 서비스 로직에서 현재 데이터 저장 로직 수정
- 냉무
> [fix] ranking 오류 수정

- src/main/java/ku/user/domain/ranking/exception/RankingGetFailException.java
- src/main/java/ku/user/domain/ranking/exception/RankingNotFoundException.java
- src/main/java/ku/user/domain/ranking/exception/RankingUpdateFailException.java
- src/main/java/ku/user/domain/ranking/exception/RedisConnectionFailException.java
- src/main/java/ku/user/domain/ranking/service/RankingServiceImpl.java
- src/main/java/ku/user/global/config/RedisConfig.java
- src/main/java/ku/user/global/exception/ErrorCode.java
- src/test/resources/application.yml
> [Feat] exception 및 설정 변경

- src/main/java/ku/user/domain/ranking/dto/request/SaveSteppingRequest.java
- src/main/java/ku/user/domain/ranking/service/RankingServiceImpl.java
> [fix] 랭킹 조회 버그 수정

- src/main/java/ku/user/domain/user/controller/UserController.java
- src/main/java/ku/user/domain/user/domain/GetUsersResponse.java
- src/main/java/ku/user/domain/user/infrastructure/entity/UserAccountStatus.java
- src/main/java/ku/user/domain/user/infrastructure/entity/UserEntity.java
- src/main/java/ku/user/domain/user/infrastructure/repository/UserRepository.java
- src/main/java/ku/user/domain/user/infrastructure/repository/UserRepositoryImpl.java
- src/main/java/ku/user/domain/user/service/UserService.java
- src/main/java/ku/user/domain/user/service/UserServiceImpl.java
- src/main/java/ku/user/global/security/AuthenticationFilter.java
- src/test/java/ku/user/user/mock/FakeUserRepository.java
매니저 서버에서 사용될 유저 정보와 정지 기능 추가
- 냉무
> [Feat] 매니저 서버에서 사용될 유저 정보와 정지 기능 추가

- src/main/java/ku/user/domain/character/controller/CharacterController.java
- src/main/java/ku/user/domain/character/dto/response/FindAllCharactersResponse.java
- src/main/java/ku/user/domain/character/service/CharacterService.java
> [feat] 모든 캐릭터 호출 api 개발
